apiVersion: v2
name: cactus-parser
description: Used to deploy parsers that load product data from a source when requested from cactus-backend
type: application
version: 0.0.4
appVersion: "0.0"
maintainers:
  - name: dataviruset
  - name: shuninghuang
dependencies:
- name: postgresql
  version: 16.7.27
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: postgresql-ha
  version: 16.3.2
  repository: https://charts.bitnami.com/bitnami
  condition: postgresqlha.enabled
- name: redis
  version: 22.0.7
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: juicefs-s3-gateway
  version: 0.11.3
  repository: https://juicedata.github.io/charts/
  condition: juicefs-s3-gateway.enabled
