{{- if and (eq .Values.kind "Deployment") .Values.autoscaling.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "cactus-backend.fullname" . }}
  labels:
    {{- include "cactus-backend.labels" . | nindent 4 }}
{{- if .Values.autoscaling.vpa.annotations }}
{{- with .Values.autoscaling.vpa.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ include "cactus-backend.fullname" . }}
      {{- with .Values.autoscaling.vpa.controlledResources }}
      controlledResources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autoscaling.vpa.maxAllowed }}
      maxAllowed:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autoscaling.vpa.minAllowed }}
      minAllowed:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  targetRef:
    apiVersion: apps/v1
    kind: "Deployment"
    name: {{ include "cactus-backend.fullname" . }}
  {{- if .Values.autoscaling.vpa.updatePolicy }}
  updatePolicy:
    {{- with .Values.autoscaling.vpa.updatePolicy.updateMode }}
    updateMode: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
