{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cactus.fullname" . }}
  labels:
    {{- include "cactus.labels" . | nindent 4 }}
type: Opaque
data:
  EXPO_PUBLIC_AMPLITUDE_PROD_API_KEY: {{ .Values.secretData.EXPO_PUBLIC_AMPLITUDE_PROD_API_KEY | b64enc | quote }}
  EXPO_PUBLIC_JOYSTICK_API_KEY: {{ .Values.secretData.EXPO_PUBLIC_JOYSTICK_API_KEY | b64enc | quote }}
  EXPO_PUBLIC_AUKI_APP_SECRET: {{ .Values.secretData.EXPO_PUBLIC_AUKI_APP_SECRET | b64enc | quote }}
{{- end }}
