apiVersion: v2
name: cactus-backend
description: A backend that exposes an API for the Cactus app to use.
type: application
version: 0.5.9
appVersion: "0.2"
maintainers:
  - name: dataviruset
  - name: shuninghuang
dependencies:
- name: postgresql
  version: 16.7.27
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: postgresql-ha
  version: 16.3.2
  repository: https://charts.bitnami.com/bitnami
  condition: postgresqlha.enabled
- name: redis
  version: 22.0.7
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: juicefs-s3-gateway
  version: 0.11.3
  repository: https://juicedata.github.io/charts/
  condition: juicefs-s3-gateway.enabled
- name: cactus-parser
  version: 0.0.3
  repository: https://charts.lookingglassprotocol.com
  condition: cactus-parser.enabled
- name: opentelemetry-collector
  version: 0.142.2
  condition: opentelemetry-collector.enabled
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
