{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cactus-parser.fullname" . }}
  labels:
    {{- include "cactus-parser.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secretData | nindent 2 }}
{{- end }}
