{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cactus-parser.fullname" . }}
  labels:
    {{- include "cactus-parser.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secretData.POSTGRES_PASSWORD | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secretData.REDIS_PASSWORD | b64enc | quote }}
  AUTH_JWT_PROFILE: {{ .Values.secretData.AUTH_JWT_PROFILE | b64enc | quote }}
{{- end }}

