apiVersion: v1
kind: Service
metadata:
  name: {{ include "cactus-parser.fullname" . }}
  labels:
    {{- include "cactus-parser.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.adminPort }}
      targetPort: {{ .Values.service.adminPort }}
      protocol: TCP
      name: admin
  selector:
    {{- include "cactus-parser.selectorLabels" . | nindent 4 }}

